name: Deploy to GitHub Pages

on:
  push:
    branches: [dev]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev # 指定检出 dev 分支

      - name: Verify file
        run: |
          echo "Current directory: $(pwd)"
          ls -R doc/  # 调试目录结构
       # 2. 调试：打印完整目录结构
      - name: Debug directory
        run: |
          echo "## 当前目录 ##"
          pwd
          echo "\n## 全部文件 ##"
          ls -R
          echo "\n## doc/ 内容 ##"
          ls -l doc/ || echo "⚠️ doc/ 不存在"

      - name: 打印测试
        run: echo "这只是一条打印信息，没有其他用途"        

      - name: Print Firebase Keys
        run: |
          echo "FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}"
          echo "FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}"
          echo "FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}"
          echo "FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}"
          echo "FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
          echo "FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}"        

      - name: Replace Firebase Configuration in HTML in doc directory
        run: |
          sed -i "s|FIREBASE_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g" doc/delete_user.html
          sed -i "s|FIREBASE_AUTH_DOMAIN|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" doc/delete_user.html
          sed -i "s|FIREBASE_PROJECT_ID|${{ secrets.FIREBASE_PROJECT_ID }}|g" doc/delete_user.html
          sed -i "s|FIREBASE_STORAGE_BUCKET|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" doc/delete_user.html
          sed -i "s|FIREBASE_MESSAGING_SENDER_ID|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" doc/delete_user.html
          sed -i "s|FIREBASE_APP_ID|${{ secrets.FIREBASE_APP_ID }}|g" doc/delete_user.html
          sed -i "s|MY_TEST_KEY|${{ secrets.MY_TEST_KEY }}|g" doc/delete_user.html
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

      - name: Output Modified HTML Content
        run: cat doc/delete_user.html   

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './doc' # 指定上传 artifact 的路径为 doc 目录

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
